In [1]:
#!pip install pymysql

In [17]:
import pandas as pd
import numpy as np

import pymysql
from sqlalchemy import create_engine



In [18]:
import getpass

In [19]:
password = getpass.getpass()

········


In [41]:
connection_string = 'mysql+pymysql://root:'+password+'@localhost/Sakila'
engine = create_engine(connection_string)
data = pd.read_sql_query('''SELECT r.rental_id, r.rental_date, i.film_id, c.name, f.title, f.rental_rate, f.rating, f.rental_duration, f.release_year from sakila.rental r join sakila.inventory i using(inventory_id) join sakila.film f on i.film_id = f.film_id join sakila.film_category fc on f.film_id = fc.film_id join sakila.category c on(fc.category_id = c.category_id)where YEAR(convert(r.rental_date,DATE)) = 2005 and YEAR(convert(r.rental_date,DATE)) is not null ;
;''', engine)

In [78]:
data.dtypes

rental_id                   int64
rental_date        datetime64[ns]
film_id                     int64
name                       object
title                      object
rental_rate               float64
rating                     object
rental_duration             int64
release_year                int64
dtype: object

In [79]:
data.head(5)

rental_id         rental_date  film_id         name             title  \
0       4863 2005-07-08 19:03:15        1  Documentary  ACADEMY DINOSAUR   
1      11433 2005-08-02 20:13:10        1  Documentary  ACADEMY DINOSAUR   
2      14714 2005-08-21 21:27:43        1  Documentary  ACADEMY DINOSAUR   
3        972 2005-05-30 20:21:07        1  Documentary  ACADEMY DINOSAUR   
4       2117 2005-06-17 20:24:00        1  Documentary  ACADEMY DINOSAUR   

   rental_rate rating  rental_duration  release_year  
0         0.99     PG                6          2006  
1         0.99     PG                6          2006  
2         0.99     PG                6          2006  
3         0.99     PG                6          2006  
4         0.99     PG                6          2006

In [80]:
data.isna().sum()

rental_id          0
rental_date        0
film_id            0
name               0
title              0
rental_rate        0
rating             0
rental_duration    0
release_year       0
dtype: int64

In [116]:
data_num = data.select_dtypes(include = np.number)
data_cat = data.select_dtypes(include = np.object)

<ipython-input-116-4d91a0760975>:2: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data_cat = data.select_dtypes(include = np.object)


In [117]:
data_cat.head()

name             title rating
0  Documentary  ACADEMY DINOSAUR     PG
1  Documentary  ACADEMY DINOSAUR     PG
2  Documentary  ACADEMY DINOSAUR     PG
3  Documentary  ACADEMY DINOSAUR     PG
4  Documentary  ACADEMY DINOSAUR     PG

In [126]:
data_cat.head()

name rating
0  Documentary     PG
1  Documentary     PG
2  Documentary     PG
3  Documentary     PG
4  Documentary     PG

In [128]:
data_cat1 = data_cat.drop(['rating'], axis=1)

In [129]:
data_cat1 

name
0      Documentary
1      Documentary
2      Documentary
3      Documentary
4      Documentary
...            ...
15857       Comedy
15858       Comedy
15859       Comedy
15860       Comedy
15861       Comedy

[15862 rows x 1 columns]

In [149]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder().fit(data_cat1)
print(encoder.categories_)
encoded = encoder.transform(data_cat1 ).toarray()
print(encoded)
onehot_encoded_name = pd.DataFrame(encoded,columns=encoder.categories_)
onehot_encoded_name.head()

[array(['Action', 'Animation', 'Children', 'Classics', 'Comedy',
       'Documentary', 'Drama', 'Family', 'Foreign', 'Games', 'Horror',
       'Music', 'New', 'Sci-Fi', 'Sports', 'Travel'], dtype=object)]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Action Animation Children Classics Comedy Documentary Drama Family Foreign  \
0    0.0       0.0      0.0      0.0    0.0         1.0   0.0    0.0     0.0   
1    0.0       0.0      0.0      0.0    0.0         1.0   0.0    0.0     0.0   
2    0.0       0.0      0.0      0.0    0.0         1.0   0.0    0.0     0.0   
3    0.0       0.0      0.0      0.0    0.0         1.0   0.0    0.0     0.0   
4    0.0       0.0      0.0      0.0    0.0         1.0   0.0    0.0     0.0   

  Games Horror Music  New Sci-Fi Sports Travel  
0   0.0    0.0   0.0  0.0    0.0    0.0    0.0  
1   0.0    0.0   0.0  0.0    0.0    0.0    0.0  
2   0.0    0.0   0.0  0.0    0.0    0.0    0.0  
3   0.0    0.0   0.0  0.0    0.0    0.0    0.0  
4   0.0    0.0   0.0  0.0    0.0    0.0    0.0

In [131]:
data_cat2 = data_cat.drop(['name'], axis=1)

In [132]:
data_cat2 

rating
0         PG
1         PG
2         PG
3         PG
4         PG
...      ...
15857  NC-17
15858  NC-17
15859  NC-17
15860  NC-17
15861  NC-17

[15862 rows x 1 columns]

In [155]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder().fit(data_cat2)
print(encoder.categories_)
encoded = encoder.transform(data_cat2).toarray()
print(encoded)
onehot_encoded_rating = pd.DataFrame(encoded,columns=encoder.categories_)
onehot_encoded_rating.head()

[array(['G', 'NC-17', 'PG', 'PG-13', 'R'], dtype=object)]
[[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


G NC-17   PG PG-13    R
0  0.0   0.0  1.0   0.0  0.0
1  0.0   0.0  1.0   0.0  0.0
2  0.0   0.0  1.0   0.0  0.0
3  0.0   0.0  1.0   0.0  0.0
4  0.0   0.0  1.0   0.0  0.0

In [182]:
cat_encoded = pd.concat([onehot_encoded_name, onehot_encoded_rating], axis=1)

In [183]:
cat_encoded

Action Animation Children Classics Comedy Documentary Drama Family  \
0        0.0       0.0      0.0      0.0    0.0         1.0   0.0    0.0   
1        0.0       0.0      0.0      0.0    0.0         1.0   0.0    0.0   
2        0.0       0.0      0.0      0.0    0.0         1.0   0.0    0.0   
3        0.0       0.0      0.0      0.0    0.0         1.0   0.0    0.0   
4        0.0       0.0      0.0      0.0    0.0         1.0   0.0    0.0   
...      ...       ...      ...      ...    ...         ...   ...    ...   
15857    0.0       0.0      0.0      0.0    1.0         0.0   0.0    0.0   
15858    0.0       0.0      0.0      0.0    1.0         0.0   0.0    0.0   
15859    0.0       0.0      0.0      0.0    1.0         0.0   0.0    0.0   
15860    0.0       0.0      0.0      0.0    1.0         0.0   0.0    0.0   
15861    0.0       0.0      0.0      0.0    1.0         0.0   0.0    0.0   

      Foreign Games  ... Music  New Sci-Fi Sports Travel    G NC-17   PG  \
0         0.0   0.0  ...   0.0  0.0    0.0    0.0    0.0  0.0   0.0  1.0   
1         0.0   0.0  ...   0.0  0.0    0.0    0.0    0.0  0.0   0.0  1.0   
2         0.0   0.0  ...   0.0  0.0    0.0    0.0    0.0  0.0   0.0  1.0   
3         0.0   0.0  ...   0.0  0.0    0.0    0.0    0.0  0.0   0.0  1.0   
4         0.0   0.0  ...   0.0  0.0    0.0    0.0    0.0  0.0   0.0  1.0   
...       ...   ...  ...   ...  ...    ...    ...    ...  ...   ...  ...   
15857     0.0   0.0  ...   0.0  0.0    0.0    0.0    0.0  0.0   1.0  0.0   
15858     0.0   0.0  ...   0.0  0.0    0.0    0.0    0.0  0.0   1.0  0.0   
15859     0.0   0.0  ...   0.0  0.0    0.0    0.0    0.0  0.0   1.0  0.0   
15860     0.0   0.0  ...   0.0  0.0    0.0    0.0    0.0  0.0   1.0  0.0   
15861     0.0   0.0  ...   0.0  0.0    0.0    0.0    0.0  0.0   1.0  0.0   

      PG-13    R  
0       0.0  0.0  
1       0.0  0.0  
2       0.0  0.0  
3       0.0  0.0  
4       0.0  0.0  
...     ...  ...  
15857   0.0  0.0  
15858   0.0  0.0  
15859   0.0  0.0  
15860   0.0  0.0  
15861   0.0  0.0  

[15862 rows x 21 columns]

In [105]:
data_num

rental_id  film_id  rental_rate  rental_duration  release_year
0           4863        1         0.99                6          2006
1          11433        1         0.99                6          2006
2          14714        1         0.99                6          2006
3            972        1         0.99                6          2006
4           2117        1         0.99                6          2006
...          ...      ...          ...              ...           ...
15857        711     1000         4.99                3          2006
15858       1493     1000         4.99                3          2006
15859       6712     1000         4.99                3          2006
15860       9701     1000         4.99                3          2006
15861      12894     1000         4.99                3          2006

[15862 rows x 5 columns]

In [106]:
data_num = data_num.drop(['release_year', 'rental_id'], axis=1)

In [107]:
data_num

film_id  rental_rate  rental_duration
0            1         0.99                6
1            1         0.99                6
2            1         0.99                6
3            1         0.99                6
4            1         0.99                6
...        ...          ...              ...
15857     1000         4.99                3
15858     1000         4.99                3
15859     1000         4.99                3
15860     1000         4.99                3
15861     1000         4.99                3

[15862 rows x 3 columns]

In [113]:
from sklearn.preprocessing import MinMaxScaler
MinMaxtransformer = MinMaxScaler().fit(data_num)
x_normalized = MinMaxtransformer.transform(data_num) #minmaxtransformer
print(x_normalized.shape)
x_normalized = pd.DataFrame(x_normalized,columns=data_num.columns)
x_normalized.head()

(15862, 3)


film_id  rental_rate  rental_duration
0      0.0          0.0             0.75
1      0.0          0.0             0.75
2      0.0          0.0             0.75
3      0.0          0.0             0.75
4      0.0          0.0             0.75

In [159]:
X = pd.concat([x_normalized, onehot_encoded_name, onehot_encoded_rating], axis=1)

In [162]:
X.head()

film_id  rental_rate  rental_duration  (Action,)  (Animation,)  \
0      0.0          0.0             0.75        0.0           0.0   
1      0.0          0.0             0.75        0.0           0.0   
2      0.0          0.0             0.75        0.0           0.0   
3      0.0          0.0             0.75        0.0           0.0   
4      0.0          0.0             0.75        0.0           0.0   

   (Children,)  (Classics,)  (Comedy,)  (Documentary,)  (Drama,)  ...  \
0          0.0          0.0        0.0             1.0       0.0  ...   
1          0.0          0.0        0.0             1.0       0.0  ...   
2          0.0          0.0        0.0             1.0       0.0  ...   
3          0.0          0.0        0.0             1.0       0.0  ...   
4          0.0          0.0        0.0             1.0       0.0  ...   

   (Music,)  (New,)  (Sci-Fi,)  (Sports,)  (Travel,)  (G,)  (NC-17,)  (PG,)  \
0       0.0     0.0        0.0        0.0        0.0   0.0       0.0    1.0   
1       0.0     0.0        0.0        0.0        0.0   0.0       0.0    1.0   
2       0.0     0.0        0.0        0.0        0.0   0.0       0.0    1.0   
3       0.0     0.0        0.0        0.0        0.0   0.0       0.0    1.0   
4       0.0     0.0        0.0        0.0        0.0   0.0       0.0    1.0   

   (PG-13,)  (R,)  
0       0.0   0.0  
1       0.0   0.0  
2       0.0   0.0  
3       0.0   0.0  
4       0.0   0.0  

[5 rows x 24 columns]

In [164]:
connection_string = 'mysql+pymysql://root:'+password+'@localhost/Sakila'
engine = create_engine(connection_string)
data2 = pd.read_sql_query('''select j1.title, j1.film_id,j1.rental_date, (month(j1.rental_date) = 08) as August_rental
from
(SELECT r.rental_id, r.rental_date, i.film_id, f.title
from sakila.rental r 
join sakila.inventory i 
using(inventory_id) 
join sakila.film f
on i.film_id = f.film_id 
where YEAR(convert(r.rental_date,DATE)) = 2005
) as  j1;;''', engine)

In [167]:
data2

title  film_id         rental_date  August_rental
0      ACADEMY DINOSAUR        1 2005-07-08 19:03:15              0
1      ACADEMY DINOSAUR        1 2005-08-02 20:13:10              1
2      ACADEMY DINOSAUR        1 2005-08-21 21:27:43              1
3      ACADEMY DINOSAUR        1 2005-05-30 20:21:07              0
4      ACADEMY DINOSAUR        1 2005-06-17 20:24:00              0
...                 ...      ...                 ...            ...
15857         ZORRO ARK     1000 2005-05-29 03:49:03              0
15858         ZORRO ARK     1000 2005-06-15 21:50:32              0
15859         ZORRO ARK     1000 2005-07-12 13:24:47              0
15860         ZORRO ARK     1000 2005-07-31 07:32:21              0
15861         ZORRO ARK     1000 2005-08-19 03:49:28              1

[15862 rows x 4 columns]

In [ ]:
#August rental 0= not rented in August, 1=rented in August

In [191]:
August_rental = data2.drop(['title','film_id', 'rental_date'], axis=1)
                            
                            

In [192]:
August_rental.head()

August_rental
0              0
1              1
2              1
3              0
4              0

In [196]:
August_rental['August_rental'].value_counts()

0    10176
1     5686
Name: August_rental, dtype: int64

In [210]:
August_rental.drop(August_rental.loc[August_rental['August_rental']==0].index, inplace=True)

In [211]:
August_rental

August_rental
1                  1
2                  1
7                  1
9                  1
10                 1
...              ...
15849              1
15854              1
15855              1
15856              1
15861              1

[5686 rows x 1 columns]

In [217]:
August_rental = August_rental_check

In [219]:
August_rental_check


August_rental
1                  1
2                  1
7                  1
9                  1
10                 1
...              ...
15849              1
15854              1
15855              1
15856              1
15861              1

[5686 rows x 1 columns]

In [221]:
y = August_rental_check['August_rental']
y.head()

1     1
2     1
7     1
9     1
10    1
Name: August_rental, dtype: int64

In [222]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

ValueError: Found input variables with inconsistent numbers of samples: [15862, 5686]

In [223]:
from sklearn.linear_model import LogisticRegression
classification = LogisticRegression(random_state=0, solver='lbfgs',
                  multi_class='multinomial').fit(X_train, y_train)

In [224]:
classification = LogisticRegression(random_state=0, solver='saga',
                  multi_class='multinomial').fit(X_train, y_train)

In [225]:
predictions = classification.predict(X_test)
classification.score(X_test, y_test)

0.6463914276709738

In [226]:
from sklearn import neighbors
clf = neighbors.KNeighborsClassifier(n_neighbors=5, weights='uniform')
clf.fit(X, y)
predictions_clf = clf.predict(X_test)
clf.score(X_test, y_test)

ValueError: Found input variables with inconsistent numbers of samples: [15862, 5686]